chmod +x ./binutils/bfd/config.bfd
chmod +x ./binutils/bfd/configure
chmod +x ./binutils/config.guess
chmod +x ./binutils/config.sub
chmod +x ./binutils/configure
chmod +x ./binutils/install-sh
chmod +x ./binutils/ltconfig
chmod +x ./binutils/missing
chmod +x ./binutils/mkdep
chmod +x ./binutils/mkinstalldirs
chmod +x ./binutils/move-if-change
chmod +x ./binutils/symlink-tree
chmod +x ./binutils/ylwrap
chmod +x ./binutils/binutils/configure
chmod +x ./binutils/binutils/ranlib.sh
chmod +x ./binutils/binutils/sanity.sh
chmod +x ./binutils/binutils/testsuite/binutils-all/windres/checkbox.rc
chmod +x ./binutils/binutils/testsuite/binutils-all/windres/combobox.rc
chmod +x ./binutils/binutils/testsuite/binutils-all/windres/edittext.rc
chmod +x ./binutils/binutils/testsuite/binutils-all/windres/listbox.rc
chmod +x ./binutils/binutils/testsuite/binutils-all/windres/msupdate
chmod +x ./binutils/binutils/testsuite/binutils-all/windres/scrollbar.rc
chmod +x ./binutils/config/acinclude.m4
chmod +x ./binutils/etc/configure
chmod +x ./binutils/gas/configure
chmod +x ./binutils/gas/testsuite/gas/hppa/parse/align1.s
chmod +x ./binutils/gas/testsuite/gas/hppa/parse/align2.s
chmod +x ./binutils/gas/testsuite/gas/hppa/parse/block1.s
chmod +x ./binutils/gas/testsuite/gas/hppa/parse/block2.s
chmod +x ./binutils/gas/testsuite/gas/hppa/parse/calldatabug.s
chmod +x ./binutils/gas/testsuite/gas/hppa/parse/entrybug.s
chmod +x ./binutils/gas/testsuite/gas/hppa/parse/exportbug.s
chmod +x ./binutils/gas/testsuite/gas/hppa/parse/fixup7bug.s
chmod +x ./binutils/gas/testsuite/gas/hppa/parse/global.s
chmod +x ./binutils/gas/testsuite/gas/hppa/parse/linesepbug.s
chmod +x ./binutils/gas/testsuite/gas/hppa/parse/lselbug.s
chmod +x ./binutils/gas/testsuite/gas/hppa/parse/nosubspace.s
chmod +x ./binutils/gas/testsuite/gas/hppa/parse/parse.exp
chmod +x ./binutils/gas/testsuite/gas/hppa/parse/procbug.s
chmod +x ./binutils/gas/testsuite/gas/hppa/parse/stringer.s
chmod +x ./binutils/gas/testsuite/gas/hppa/parse/undefbug.s
chmod +x ./binutils/gas/testsuite/gas/hppa/parse/versionbug.s
chmod +x ./binutils/gas/testsuite/gas/hppa/reloc/blebug.s
chmod +x ./binutils/gas/testsuite/gas/hppa/reloc/blebug2.s
chmod +x ./binutils/gas/testsuite/gas/hppa/reloc/blebug3.s
chmod +x ./binutils/gas/testsuite/gas/hppa/reloc/labelopbug.s
chmod +x ./binutils/gas/testsuite/gas/hppa/reloc/plabelbug.s
chmod +x ./binutils/gas/testsuite/gas/hppa/reloc/reduce.s
chmod +x ./binutils/gas/testsuite/gas/hppa/reloc/reloc.exp
chmod +x ./binutils/gas/testsuite/gas/hppa/unsorted/labeldiffs.s
chmod +x ./binutils/gas/testsuite/gas/hppa/unsorted/locallabel.s
chmod +x ./binutils/gas/testsuite/gas/hppa/unsorted/ss_align.s
chmod +x ./binutils/gas/testsuite/gas/hppa/unsorted/unsorted.exp
chmod +x ./binutils/gas/testsuite/gas/ppc/generate.sh
chmod +x ./binutils/gas/testsuite/gas/tic4x/rebuild.sh
chmod +x ./binutils/gas/testsuite/lib/doobjcmp
chmod +x ./binutils/gas/testsuite/lib/doboth
chmod +x ./binutils/gas/testsuite/lib/dostriptest
chmod +x ./binutils/gas/testsuite/lib/dotest
chmod +x ./binutils/gas/testsuite/lib/dounsreloc
chmod +x ./binutils/gas/testsuite/lib/dounssym
chmod +x ./binutils/gas/testsuite/lib/run
chmod +x ./binutils/gprof/bbconv.pl
chmod +x ./binutils/gprof/configure
chmod +x ./binutils/intl/configure
chmod +x ./binutils/intl/linux-msg.sed
chmod +x ./binutils/intl/po2tbl.sed.in
chmod +x ./binutils/intl/xopen-msg.sed
chmod +x ./binutils/ld/emulparams/elf32bmipn32.sh
chmod +x ./binutils/ld/emulparams/elf32fr30.sh
chmod +x ./binutils/ld/emulparams/elf32frv.sh
chmod +x ./binutils/ld/emulparams/elf32iq10.sh
chmod +x ./binutils/ld/emulparams/elf32iq2000.sh
chmod +x ./binutils/ld/emulparams/elf32openrisc.sh
chmod +x ./binutils/ld/emulparams/elf64bmip.sh
chmod +x ./binutils/ld/emulparams/elf64hppa.sh
chmod +x ./binutils/ld/emulparams/i386beos.sh
chmod +x ./binutils/ld/emulparams/zpuelf.sh
chmod +x ./binutils/ld/configure
chmod +x ./binutils/ld/genscripts.sh
chmod +x ./binutils/ld/scripttempl/zpu.sc
chmod +x ./binutils/ld/testsuite/ld-auto-import/auto-import.exp
chmod +x ./binutils/ld/testsuite/ld-auto-import/client.c
chmod +x ./binutils/ld/testsuite/ld-auto-import/dll.c
chmod +x ./binutils/libiberty/configure
chmod +x ./binutils/opcodes/configure
chmod +x ./gcc/config.guess
chmod +x ./gcc/config.rpath
chmod +x ./gcc/config.sub
chmod +x ./gcc/configure
chmod +x ./gcc/install-sh
chmod +x ./gcc/ltconfig
chmod +x ./gcc/missing
chmod +x ./gcc/mkdep
chmod +x ./gcc/mkinstalldirs
chmod +x ./gcc/move-if-change
chmod +x ./gcc/symlink-tree
chmod +x ./gcc/ylwrap
chmod +x ./gcc/boehm-gc/callprocs
chmod +x ./gcc/boehm-gc/config.guess
chmod +x ./gcc/boehm-gc/config.sub
chmod +x ./gcc/boehm-gc/configure
chmod +x ./gcc/boehm-gc/depcomp
chmod +x ./gcc/boehm-gc/install-sh
chmod +x ./gcc/boehm-gc/ltconfig
chmod +x ./gcc/boehm-gc/mkinstalldirs
chmod +x ./gcc/contrib/reghunt/reg_periodic
chmod +x ./gcc/contrib/reghunt/reg_search
chmod +x ./gcc/contrib/reghunt/reg_test_template
chmod +x ./gcc/contrib/analyze_brprob
chmod +x ./gcc/contrib/compare_tests
chmod +x ./gcc/contrib/convert_to_f2c
chmod +x ./gcc/contrib/convert_to_g2c
chmod +x ./gcc/contrib/download_f2c
chmod +x ./gcc/contrib/gcc_build
chmod +x ./gcc/contrib/gcc_update
chmod +x ./gcc/contrib/gennews
chmod +x ./gcc/contrib/index-prop
chmod +x ./gcc/contrib/newcvsroot
chmod +x ./gcc/contrib/test_installed
chmod +x ./gcc/contrib/test_summary
chmod +x ./gcc/contrib/texi2pod.pl
chmod +x ./gcc/contrib/warn_summary
chmod +x ./gcc/contrib/regression/btest-gcc.sh
chmod +x ./gcc/contrib/regression/objs-gcc.sh
chmod +x ./gcc/fastjar/configure
chmod +x ./gcc/gcc/configure
chmod +x ./gcc/gcc/fixproto
chmod +x ./gcc/gcc/gccbug.in
chmod +x ./gcc/gcc/move-if-change
chmod +x ./gcc/gcc/scan-types.sh
chmod +x ./gcc/gcc/sort-protos
chmod +x ./gcc/gcc/doc/install.texi2html
chmod +x ./gcc/gcc/fixinc/fixincl.sh
chmod +x ./gcc/gcc/fixinc/genfixes
chmod +x ./gcc/gcc/fixinc/mkfixinc.sh
chmod +x ./gcc/gcc/testsuite/ada/acats/run_acats
chmod +x ./gcc/gcc/testsuite/ada/acats/run_all.sh
chmod +x ./gcc/intl/configure
chmod +x ./gcc/libf2c/libF77/configure
chmod +x ./gcc/libf2c/configure
chmod +x ./gcc/libf2c/libI77/configure
chmod +x ./gcc/libf2c/libU77/configure
chmod +x ./gcc/libffi/configure
chmod +x ./gcc/libiberty/configure
chmod +x ./gcc/libjava/addr2name.awk
chmod +x ./gcc/libjava/configure
chmod +x ./gcc/libjava/libltdl/config.guess
chmod +x ./gcc/libjava/libltdl/config.sub
chmod +x ./gcc/libjava/libltdl/configure
chmod +x ./gcc/libjava/libltdl/install-sh
chmod +x ./gcc/libjava/libltdl/missing
chmod +x ./gcc/libjava/libltdl/mkinstalldirs
chmod +x ./gcc/libjava/scripts/unicode-blocks.pl
chmod +x ./gcc/libjava/scripts/unicode-decomp.pl
chmod +x ./gcc/libjava/scripts/unicode-muncher.pl
chmod +x ./gcc/libobjc/configure
chmod +x ./gcc/libstdc++-v3/configure
chmod +x ./gcc/libstdc++-v3/docs/doxygen/filter
chmod +x ./gcc/libstdc++-v3/scripts/check_performance
chmod +x ./gcc/libstdc++-v3/scripts/check_survey.in
chmod +x ./gcc/libstdc++-v3/scripts/create_testsuite_files
chmod +x ./gcc/libstdc++-v3/scripts/extract_symvers
chmod +x ./gcc/libstdc++-v3/scripts/testsuite_flags.in
chmod +x ./gcc/maintainer-scripts/gcc_release
chmod +x ./gcc/maintainer-scripts/maintainer-addresses
chmod +x ./gcc/maintainer-scripts/update_version
chmod +x ./gcc/maintainer-scripts/update_web_docs
chmod +x ./gcc/maintainer-scripts/update_web_docs_libstdcxx
chmod +x ./gcc/maintainer-scripts/update_web_docs_old
chmod +x ./gcc/zlib/configure
chmod +x ./gdb/etc/configure
chmod +x ./gdb/config.guess
chmod +x ./gdb/config.sub
chmod +x ./gdb/configure
chmod +x ./gdb/djunpack.bat
chmod +x ./gdb/install-sh
chmod +x ./gdb/ltconfig
chmod +x ./gdb/missing
chmod +x ./gdb/mkinstalldirs
chmod +x ./gdb/move-if-change
chmod +x ./gdb/symlink-tree
chmod +x ./gdb/ylwrap
chmod +x ./gdb/config/acinclude.m4
chmod +x ./gdb/gdb/doc/configure
chmod +x ./gdb/gdb/configure
chmod +x ./gdb/gdb/gdb-events.sh
chmod +x ./gdb/gdb/gdb_gcore.sh
chmod +x ./gdb/gdb/gdb_indent.sh
chmod +x ./gdb/gdb/gdb_mbuild.sh
chmod +x ./gdb/gdb/gdbarch.sh
chmod +x ./gdb/gdb/observer.sh
chmod +x ./gdb/gdb/gdbserver/configure
chmod +x ./gdb/gdb/nlm/configure
chmod +x ./gdb/gdb/rdi-share/configure
chmod +x ./gdb/gdb/regformats/regdat.sh
chmod +x ./gdb/gdb/testsuite/configure
chmod +x ./gdb/gdb/testsuite/gdb.hp/gdb.aCC/configure
chmod +x ./gdb/gdb/testsuite/gdb.hp/configure
chmod +x ./gdb/gdb/testsuite/gdb.hp/gdb.base-hp/configure
chmod +x ./gdb/gdb/testsuite/gdb.hp/gdb.base-hp/so-thresh.sh
chmod +x ./gdb/gdb/testsuite/gdb.hp/gdb.compat/configure
chmod +x ./gdb/gdb/testsuite/gdb.hp/gdb.defects/configure
chmod +x ./gdb/gdb/testsuite/gdb.hp/gdb.objdbg/configure
chmod +x ./gdb/gdb/testsuite/gdb.hp/gdb.objdbg/tools/symaddr.pa64
chmod +x ./gdb/gdb/testsuite/gdb.hp/gdb.objdbg/tools/symaddr
chmod +x ./gdb/gdb/testsuite/gdb.hp/tools/odump
chmod +x ./gdb/gdb/testsuite/gdb.stabs/configure
chmod +x ./gdb/intl/configure
chmod +x ./gdb/mmalloc/configure
chmod +x ./gdb/readline/configure
chmod +x ./gdb/readline/doc/texi2dvi
chmod +x ./gdb/readline/doc/texi2html
chmod +x ./gdb/readline/support/config.guess
chmod +x ./gdb/readline/support/config.sub
chmod +x ./gdb/readline/support/install.sh
chmod +x ./gdb/readline/support/mkdirs
chmod +x ./gdb/readline/support/mkdist
chmod +x ./gdb/readline/support/shlib-install
chmod +x ./gdb/readline/support/shobj-conf
chmod +x ./gdb/sim/arm/configure
chmod +x ./gdb/sim/d10v/configure
chmod +x ./gdb/sim/configure
chmod +x ./gdb/sim/common/configure
chmod +x ./gdb/sim/d30v/configure
chmod +x ./gdb/sim/erc32/configure
chmod +x ./gdb/sim/frv/configure
chmod +x ./gdb/sim/h8300/configure
chmod +x ./gdb/sim/h8500/configure
chmod +x ./gdb/sim/i960/configure
chmod +x ./gdb/sim/igen/compare_igen_models
chmod +x ./gdb/sim/igen/configure
chmod +x ./gdb/sim/m32r/configure
chmod +x ./gdb/sim/m68hc11/configure
chmod +x ./gdb/sim/mcore/configure
chmod +x ./gdb/sim/mips/configure
chmod +x ./gdb/sim/mn10200/configure
chmod +x ./gdb/sim/mn10300/configure
chmod +x ./gdb/sim/ppc/configure
chmod +x ./gdb/sim/sh/configure
chmod +x ./gdb/sim/testsuite/configure
chmod +x ./gdb/sim/testsuite/d10v-elf/configure
chmod +x ./gdb/sim/testsuite/d30v-elf/configure
chmod +x ./gdb/sim/testsuite/fr30-elf/configure
chmod +x ./gdb/sim/testsuite/frv-elf/configure
chmod +x ./gdb/sim/testsuite/m32r-elf/configure
chmod +x ./gdb/sim/testsuite/mips64el-elf/configure
chmod +x ./gdb/sim/v850/configure
chmod +x ./gdb/sim/z8k/configure
chmod +x ./gdb/utils/spu/configure
chmod +x ./gdb/utils/configure
chmod +x ./gdb/utils/wince/configure
